var res = {
    // Common
    HomeBtn_png : "res/HomeBtn.png",
    HomeBtn_s_png : "res/HomeBtn_selected.png",
    Twitter_png : "res/Twitter.png",
    Facebook_png : "res/Facebook.png",
    // Share(finnally unnecessary)
    ShareBG_png : "res/ShareBG.png",
    ShareBtn_s_png : "res/shareBtn_selected.png",
    ShareBtn_png : "res/shareBtn.png",
    BackBtn_s_png : "res/backBtn_selected.png",
    BackBtn_png : "res/backBtn.png",
    Clear_png : "res/Clear.png",
    // TOP
    Splash_png : "res/Splash.png",
    Top_png : "res/Top.png",
    StartBtn_s_png : "res/StartBtn_selected.png",
    StartBtn_png : "res/StartBtn.png",
    OtherBtn_s_png : "res/OtherBtn_selected.png",
    OtherBtn_png : "res/OtherBtn.png",
    Bonus_1_png : "res/bonus1.png",
    Bonus_2_png : "res/bonus2.png",
    Bonus_3_png : "res/bonus3.png",
    OkBtn_png : "res/okBtn.png",
    OkBtn_s_png : "res/okBtn_selected.png",
    closeBtn_png : "res/closeBtn.png",
    closeBtn_s_png : "res/closeBtn_selected.png",
    // Tutorial
    Tutlrial_0_png : "res/Tutorial0.png",
    Tutlrial_1_png : "res/Tutorial1.png",
    Tutlrial_2_png : "res/Tutorial2.png",
    Tutlrial_3_png : "res/Tutorial3.png",
    Tutlrial_4_png : "res/Tutorial4.png",
    Tutlrial_5_png : "res/Tutorial5.png",
    AboutSave_1_png : "res/aboutSave1.png",
    AboutSave_2_png : "res/aboutSave2.png",
    AboutSave_3_png : "res/aboutSave3.png",
    AboutSave_4_png : "res/aboutSave4.png",
    TutorialNaviBG_png : "res/tutorialNaviBG.png",
    PrologueBtn_png : "res/prologueBtn.png",
    PrologueBtn_s_png : "res/prologueBtn_selected.png",
    AboutSaveBtn_png : "res/aboutSaveBtn.png",
    AboutSaveBtn_s_png : "res/aboutSaveBtn_selected.png",
    // Other
    CollectionBtn_png : "res/CollectionBtn.png",
    CollectionBtn_s_png : "res/CollectionBtn_selected.png",
    StatusBtn_png : "res/StatusBtn.png",
    StatusBtn_s_png : "res/StatusBtn_selected.png",
    TimeattackBtn_png : "res/TimeattackBtn.png",
    TimeattackBtn_s_png : "res/TimeattackBtn_selected.png",
    MoreBtn_png : "res/MoreBtn.png",
    MoreBtn_s_png : "res/MoreBtn_selected.png",
    OtherBG_png : "res/OtherBG.png",
    RankingBG_png : "res/RankingBG.png",
    // Shopping
    loading_png : "res/loading.png",
    shoppingBG_png : "res/shoppingBG.png",
    TutorialBtn_png : "res/tutorialBtn.png",
    TutorialBtn_s_png : "res/tutorialBtn_selected.png",
    restoreBtn_png : "res/restoreBtn.png",
    restoreBtn_s_png : "res/restoreBtn_selected.png",
    item1_png : "res/item1.png",
    item2_png : "res/item2.png",
    item3_png : "res/item3.png",
    item4_png : "res/item4.png",
    item5_png : "res/item5.png",
    item6_png : "res/item6.png",
    point1_png : "res/point1.png",
    point1_s_png : "res/point1_selected.png",
    point2_png : "res/point2.png",
    point2_s_png : "res/point2_selected.png",
    point3_png : "res/point3.png",
    point3_s_png : "res/point3_selected.png",
    point4_png : "res/point4.png",
    point4_s_png : "res/point4_selected.png",
    point5_png : "res/point5.png",
    point5_s_png : "res/point5_selected.png",
    point6_png : "res/point6.png",
    point6_s_png : "res/point6_selected.png",
    price1_png : "res/price1.png",
    price1_s_png : "res/price1_selected.png",
    price2_png : "res/price2.png",
    price2_s_png : "res/price2_selected.png",
    price3_png : "res/price3.png",
    price3_s_png : "res/price3_selected.png",
    price4_png : "res/price4.png",
    price4_s_png : "res/price4_selected.png",
    price5_png : "res/price5.png",
    price5_s_png : "res/price5_selected.png",
    price6_png : "res/price6.png",
    price6_s_png : "res/price6_selected.png",
    // Ready
    Intro_png : "res/Intro.png",
    Timeattack_png : "res/Timeattack.png",
    GoBtn_s_png : "res/GoBtn_selected.png",
    GoBtn_s2_png : "res/GoBtn_selected2.png",
    GoBtn_png : "res/GoBtn.png",
    // Play
    CD_1_png : "res/countdown_1.png",
    CD_2_png : "res/countdown_2.png",
    CD_3_png : "res/countdown_3.png",
    Instruction_png : "res/instructionCover.png",
    Hard_png : "res/HardBG.png",
    ReadyBG_png : "res/ReadyBG2.png",
    HUD_png : "res/HUD.png",
    Fuck_png : "res/Fuck.png",
    bom_png : "res/bom.png",
    Fail_png : "res/fail.png",
    Goal_png : "res/Goal.png",
    Win_png : "res/Win.png",
    Lose_png : "res/Lose.png",
    CalloutCheer_png : "res/callout_cheer.png",
    Saveline_png : "res/saveline.png",
    // Referecne
    ReferenceCover_png : "res/ReferenceCover.png",
    ReferenceBG_png : "res/ReferenceBG.png",
    ReferenceBtn_png :"res/ReferenceBtn.png",
    ReferenceBtn_s_png : "res/ReferenceBtn_selected.png",
    RemoveBtn_png : "res/RemoveBtn.png",
    RemoveBtn_s_png : "res/RemoveBtn_selected.png",
    dustboxBtn_png : "res/dustbox_default.png",
    dustboxBtn_s_png : "res/dustbox_open.png",
    // Phrase
    Result_png : "res/Result.png",
    RetryBtn_s_png : "res/retryBtn_selected.png",
    RetryBtn_png : "res/retryBtn.png",
    Ugly_normal_png : "res/ugly_normal.png",
    Callout_beauty_png : "res/callout_beauty.png",
    Callout_ugly_png : "res/callout_ugly.png",
    Ugly_win_png : "res/ugly_win.png",
    Ugly_lose_png : "res/ugly_lose.png",
    Silence_png : "res/Silence.png",
    ProgressBG_png : "res/barBG.png",
    Progress_png : "res/bar.png",
    Skip_png : "res/skipBtn.png",
    Skip_s_png : "res/skipBtn_selected.png",
    White_png : "res/White.png",
    // Collection
    CollectionBG_png : "res/CollectionBG.png",
    CollectionItemBtn_png : "res/CollectionItemBtn.png",
    CollectionItemBtn_s_png : "res/CollectionItemBtn_disabled.png",
    ReplayBtn_s_png : "res/replayBtn_selected.png",
    ReplayBtn_png : "res/replayBtn.png",
    ChangeBtn_png : "res/changeBtn.png",
    ChangeBtn_s_png : "res/changeBtn_selected.png",
    // Profile
    Status_bg_png : "res/StatusBG.png",
    StatusTitle_png : "res/StatusTitle.png",
    // result
    SaveBtn_png : "res/SaveBtn.png",
    SaveBtn_s_png : "res/SaveBtn_selected.png",
    ContinueBtn_png : "res/ContinueBtn.png",
    ContinueBtn_s_png : "res/ContinueBtn_selected.png",
    CancelBtn_png : "res/CancelBtn.png",
    CancelBtn_s_png : "res/CancelBtn.png",
    ResultBG_png : "res/Result_bg.png",
    // shop
    Item1_png : "res/ShopItem1.png",
    Item2_png : "res/ShopItem2.png",
    Item3_png : "res/ShopItem3.png",
    ShopBG_png : "res/ShopList_bg.png",
    Cover_png : "res/result_cover.png"
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}